import { Raleway, Instrument_Serif } from 'next/font/google'
import "./globals.css";
import PageTransition from '@/sections/PageTransition';
import SmoothScroll from '@/sections/SmoothScroll';


const raleway = Raleway({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-raleway',
})

const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal', 'italic'],
  variable: '--font-instrument-serif',
})

export const metadata = {
  title: "PixLyne - ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${instrumentSerif.variable} bg-black antialiased`}
      >
        <SmoothScroll>
          <PageTransition>
            {children}
          </PageTransition>
        </SmoothScroll>

      </body>
    </html>
  );
}